home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /home/

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
